In [ ]:
import numpy as np
import torch

In [ ]:
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [ ]:
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[-1.2294,  0.0493,  0.5886],
        [-0.0858,  1.6089, -1.8977]], requires_grad=True)
tensor([-0.0673,  1.4658], requires_grad=True)


In [ ]:
def model(x):
    return x @ w.t() + b

preds = model(inputs)
print(preds)
print(targets)

tensor([[ -61.1982,   21.3996],
        [ -69.9311,   13.7911],
        [ -66.2768,   99.5301],
        [-101.5649,   -8.3158],
        [ -38.9590,   17.1635]], grad_fn=<AddBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [ ]:
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()
loss = mse(preds, targets)
print(loss)

tensor(12977.5527, grad_fn=<DivBackward0>)


In [ ]:
loss.backward()
print(w)
print(w.grad)


tensor([[-1.2294,  0.0493,  0.5886],
        [-0.0858,  1.6089, -1.8977]], requires_grad=True)
tensor([[-12161.6143, -12980.5332,  -7990.8398],
        [ -5208.9277,  -5428.0908,  -3683.5347]])


In [ ]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [ ]:
preds = model(inputs)
print(preds)


tensor([[ -61.1982,   21.3996],
        [ -69.9311,   13.7911],
        [ -66.2768,   99.5301],
        [-101.5649,   -8.3158],
        [ -38.9590,   17.1635]], grad_fn=<AddBackward0>)


In [ ]:
with torch.no_grad():
    w -= w.grad * 0.00001
    b -= b.grad * 0.00001
    w.grad.zero_()
    b.grad.zero_()

In [ ]:
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(12977.5527, grad_fn=<DivBackward0>)


In [ ]:
for i in range(10000):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 0.00001
        b -= b.grad * 0.00001
        w.grad.zero_()
        b.grad.zero_()

In [ ]:
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(0.5493, grad_fn=<DivBackward0>)


In [ ]:
print(preds)
print(targets)

tensor([[ 57.1547,  70.5569],
        [ 82.2140, 100.5133],
        [118.6936, 132.9214],
        [ 21.0826,  36.9849],
        [101.9198, 119.1744]], grad_fn=<AddBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
