In [ ]:
import torch.nn as nn
import torch
import numpy as np

In [ ]:
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], 
                   [102, 43, 37], [69, 96, 70], [73, 67, 43], 
                   [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70], [73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], 
                    [22, 37], [103, 119], [56, 70], 
                    [81, 101], [119, 133], [22, 37], 
                    [103, 119], [56, 70], [81, 101], 
                    [119, 133], [22, 37], [103, 119]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [ ]:
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader
train_ds = TensorDataset(inputs, targets)

In [ ]:
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [ ]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 73.,  67.,  43.],
        [ 87., 134.,  58.],
        [ 73.,  67.,  43.]])
tensor([[119., 133.],
        [ 22.,  37.],
        [ 56.,  70.],
        [119., 133.],
        [ 56.,  70.]])


In [ ]:
model = nn.Linear(3,2) #(input,output) #initializes weights and biases
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.5590,  0.2912,  0.3588],
        [ 0.3045, -0.4662, -0.1345]], requires_grad=True)
Parameter containing:
tensor([ 0.1433, -0.4998], requires_grad=True)


In [ ]:
preds = model(inputs)
preds

tensor([[ 75.8860, -15.2905],
        [ 99.5972, -22.4247],
        [108.6014, -44.2819],
        [ 82.9564,   5.5375],
        [ 91.7813, -33.6615],
        [ 75.8860, -15.2905],
        [ 99.5972, -22.4247],
        [108.6014, -44.2819],
        [ 82.9564,   5.5375],
        [ 91.7813, -33.6615],
        [ 75.8860, -15.2905],
        [ 99.5972, -22.4247],
        [108.6014, -44.2819],
        [ 82.9564,   5.5375],
        [ 91.7813, -33.6615]], grad_fn=<AddmmBackward>)

In [ ]:
import torch.nn.functional as F

In [ ]:
loss_fn = F.mse_loss
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(8292.3379, grad_fn=<MseLossBackward>)


In [ ]:
opt = torch.optim.SGD(model.parameters(), lr=0.00001)

In [ ]:
#final model trainer
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [ ]:
fit(200, model, loss_fn, opt,train_dl)
preds = model(inputs)
print(preds)
print(targets)

Epoch [10/200], Loss: 2.7142
Epoch [20/200], Loss: 4.8120
Epoch [30/200], Loss: 4.0721
Epoch [40/200], Loss: 3.2838
Epoch [50/200], Loss: 3.4639
Epoch [60/200], Loss: 3.7586
Epoch [70/200], Loss: 4.8272
Epoch [80/200], Loss: 3.6210
Epoch [90/200], Loss: 3.1087
Epoch [100/200], Loss: 1.7108
Epoch [110/200], Loss: 1.1349
Epoch [120/200], Loss: 2.6064
Epoch [130/200], Loss: 2.1502
Epoch [140/200], Loss: 2.2045
Epoch [150/200], Loss: 2.3645
Epoch [160/200], Loss: 2.3850
Epoch [170/200], Loss: 1.9702
Epoch [180/200], Loss: 1.9529
Epoch [190/200], Loss: 1.6518
Epoch [200/200], Loss: 2.2272
tensor([[ 57.2523,  70.3404],
        [ 81.6974,  99.6729],
        [119.7339, 135.1055],
        [ 21.3803,  37.6345],
        [100.8851, 116.9482],
        [ 57.2523,  70.3404],
        [ 81.6974,  99.6729],
        [119.7339, 135.1055],
        [ 21.3803,  37.6345],
        [100.8851, 116.9482],
        [ 57.2523,  70.3404],
        [ 81.6974,  99.6729],
        [119.7339, 135.1055],
        [ 21.3803, 